# Default values for ..
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  # defult registry server for Docker Hub
  registry: "https://index.docker.io/v1/"
  name: kubeact
  tag: latest
  username: 
  password: 
  pullPolicy: IfNotPresent


