# Default values for ..
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: < Enter your image repository >
  tag: latest
  pullPolicy: IfNotPresent

imagePullSecrets: []
