apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}-deployment
  labels:
    app: {{ .Chart.Name }}-runner
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}-runner
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}-runner
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.username }}/{{ .Values.image.name }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        
      imagePullSecrets:
        - name: {{ .Values.image.name }}-pull-secret
